# Generated by Django 4.0.3 on 2022-03-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departments_jobposition_employeedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='department',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
    ]
